import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../../components/NavBar";

export const metadata: Metadata = {
  title: "Yacker's OPTCG Tournaments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footer = <footer>Made by KARUNESWARAN Jack</footer>;
  return (
    <html
      lang="en"
      className="text-black bg-white dark:text-white dark:bg-black"
    >
      <body className="antialiased max-w-xl mx-4 mt-8 lg:mx-auto">
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          <Navbar />
          {children}
          {footer}
        </main>
      </body>
    </html>
  );
}
